### ISSUE TITLE
como arreglar el layout al colapsarse

### ISSUE THREAD

**Issue by ChrisVilches** [FeloVilches/mo-plugin-repository-front-end#6]
`app.component.scss`

```css

@mixin link-color($color) {
  .fa {
    color: $color;
    /*font-size: 20px;
    padding: 5px;*/
  }
}
```

`app.component.html`

```html
<a class="navbar-brand" routerLink="/"><!--<img src="assets/mo63x63.png">--></a>
```

Si se comenta las lineas como estan ahi comentadas, se arregla el problema de espacio (arriba) al colapsar.
